import bcrypt from 'bcryptjs'
const data = {
  users: [
    {
      name:'naveed',
      email:'shoukat.naveed@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin:true,
    },
    {
      name:'hamdan',
      email:'hamdan.ahmed@gmail.com',
      password: bcrypt.hashSync('987654'),
      isAdmin:false,
    },
  ],
  products: [
    {
      name: 'Cotton Shirt',
      slug: 'cotton-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      isFeatured: true,
      featuredImage: '/images/banner1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Nike shirt made in Turkey',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 3.5,
      numReviews: 20,
      countInStock: 10,
      description: 'Adidas shirt made in Turkey',
    },
    {
      name: 'Slim Fit Shirt',
      slug: 'slim-fit-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 120,
      brand: 'Marka',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Marka Slim fit shirt made in Turkey',
    },
    {
      name: 'Golf Paint',
      slug: 'golf-paint',
      category: 'Paints',
      image: '/images/pants1.jpg',
      price: 150,
      brand: 'Nike',
      rating: 4.8,
      numReviews: 38,
      countInStock: 8,
      description: 'Nike Golf Paint made in Turkey',
    },
    {
      name: 'Cotton Paint',
      slug: 'cotton-paint',
      category: 'Paints',
      image: '/images/pants2.jpg',
      price: 40,
      brand: 'Marka',
      rating: 3.9,
      numReviews: 38,
      countInStock: 80,
      description: 'Marka Paint made in Turkey',
    },
    {
      name: 'Classic Paint',
      slug: 'classic-paint',
      category: 'Paints',
      image: '/images/pants3.jpg',
      price: 60,
      brand: 'Moka',
      rating: 4.1,
      numReviews: 75,
      countInStock: 7,
      description: 'Moka Paint made in Turkey',
    },

  ]
}

export default data;